#!/bin/env perl

use v5.38;
use utf8;
use strict;
use FindBin;

# f16_sqrt.txt is generated by TestFloat-3b/testfloat_gen.
# http://www.jhauser.us/arithmetic/TestFloat.html
# $ ./testfloat_gen -level 2 f16_sqrt > f16_sqrt.txt
open my $fh, "<", "$FindBin::Bin/f16_sqrt.txt" or die "Can't open f16_sqrt.txt: $!";

say <<EOF;
// Code generated by scripts/f16_sqrt.pl; DO NOT EDIT.

package float16

var f16Sqrt = []struct {
    x uint16
    y uint16
} {
EOF
while(my $line = <$fh>) {
    chomp $line;
    my ($x, $y, undef) = split /\s+/, $line;
    say "    {0x$x, 0x$y},";
}

say "}";

close $fh;
