#!/bin/env perl

use v5.38;
use utf8;
use strict;
use FindBin;

# f16_add.txt is generated by TestFloat-3b/testfloat_gen.
# http://www.jhauser.us/arithmetic/TestFloat.html
# $ ./testfloat_gen -level 2 f16_add > f64_to_f16.txt
open my $fh, "<", "$FindBin::Bin/f16_add.txt" or die "Can't open f16_add.txt: $!";

say <<EOF;
// Code generated by scripts/f16_add.pl; DO NOT EDIT.

package float16

var f16Add = []struct {
    a, b Float16
    want Float16
} {
EOF
while(my $line = <$fh>) {
    chomp $line;
    my ($a, $b, $c, undef) = split /\s+/, $line;
    say "    {0x$a, 0x$b, 0x$c},";
}

say "}";

close $fh;
