#!/bin/env perl

use v5.38;
use utf8;
use strict;
use FindBin;

# f64_to_f16.txt is generated by TestFloat-3b/testfloat_gen.
# http://www.jhauser.us/arithmetic/TestFloat.html
# $ ./testfloat_gen -level 2 f64_to_f16 > f64_to_f16.txt
open my $fh, "<", "$FindBin::Bin/f64_to_f16.txt" or die "Can't open f64_to_f16.txt: $!";

say <<EOF;
// Code generated by scripts/f64_to_f16.pl; DO NOT EDIT.

package float16

var f64ToF16 = []struct {
    f64 uint64
    f16 uint16
} {
EOF
while(my $line = <$fh>) {
    chomp $line;
    my ($f64, $f16, undef) = split /\s+/, $line;
    say "    {0x$f64, 0x$f16},";
}

say "}";

close $fh;
