name: test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.24"
          - "1.23"
          - "1.22"
          - "1.21"
        arch:
          - amd64
          - "386"
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            go test -coverprofile="coverage.txt" -timeout 6h -v ./...
          else
            go test -coverprofile="coverage.txt" -timeout 10m -short -v ./...
          fi
        env:
          GOARCH: ${{ matrix.arch }}
      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          flags: ${{ matrix.go }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
